# See https://prek.j178.dev for more information
repos:
  # https://prek.j178.dev/builtin/
  - repo: builtin
    hooks:
      - id: no-commit-to-branch
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  # Run fortitude linter, https://fortitude.readthedocs.io/
  - repo: https://github.com/PlasmaFAIR/fortitude-pre-commit
    rev: v0.8.0
    hooks:
      - id: fortitude
        args: ["--fix"]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        files: 'run_fms_tc.sh'

  - repo: local
    hooks:
      - id: module-usage
        name: Check module usage
        language: system
        entry: ./check_modules.sh
        files: '.[fF]90$'
        pass_filenames: true

      # fprettify autoformatter
      - id: format
        name: Format Fortran code
        language: python
        entry: ./autoformat.py
        files: '.[fF]90$'
        pass_filenames: true
        exclude: unit_tests/testdrive.F90
