#!/bin/sh

set -eu

output=$1
tmp="${output}.tmp"

# Collect build settings from the Makefile/CMake environment, with fallbacks
# for running the script by hand.
source_dir=${OPENFMS_SOURCE_DIR:-.}
version=${OPENFMS_VERSION:-}
backend=${OPENFMS_BACKEND:-unknown}
build_system=${OPENFMS_BUILD_SYSTEM:-unknown}
build_type=${OPENFMS_BUILD_TYPE:-unknown}
fc=${OPENFMS_FC:-unknown}
fc_id=${OPENFMS_FC_ID:-unknown}
fc_version=${OPENFMS_FC_VERSION:-}
fflags=${OPENFMS_FFLAGS:-}
build_date=${OPENFMS_BUILD_DATE:-$(date '+%Y-%m-%d %H:%M:%S %z')}

# Collect git information
git_branch=unknown
git_revision=unknown
git_dirty=

if command -v git >/dev/null 2>&1; then
   git_branch=$(git -C "$source_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
   git_revision=$(git -C "$source_dir" rev-parse HEAD 2>/dev/null || echo unknown)
   if test -n "$(git -C "$source_dir" status --porcelain 2>/dev/null)"; then
      git_dirty=+
   fi
fi

mkdir -p "$(dirname "$output")"

# Function to add a Fortran character parameter
# definition in the generated build_info
emit_string() {
   name=$1
   value=$2
   escaped=$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/""/g')
   awk -v name="$name" -v value="$escaped" '
      BEGIN {
         chunk_size = 56
         printf "   character(len=*), parameter :: %s = &\n", name
         if (length(value) == 0) {
            print "      \"\""
            exit
         }
         for (i = 1; i <= length(value); i += chunk_size) {
            chunk = substr(value, i, chunk_size)
            if (i + chunk_size <= length(value)) {
               printf "      \"%s\" // &\n", chunk
            } else {
               printf "      \"%s\"\n", chunk
            }
         }
      }
   '
}

# Removes build date from the generated file
# Needed to check if there are no changes except for the timestamp (see below)
remove_build_date() {
   awk '
      /parameter :: BUILD_DATE = &/ {
         print
         getline
         print "      \"<build-date>\""
         next
      }
      { print }
   ' "$1"
}

# Generate into a temporary file first. The final file is only replaced below
# when the generated contents changed in a meaningful way (not only timestamp)
{
   printf '! This file is generated by generate_build_info.sh.\n'
   printf 'subroutine print_build_info(unit)\n'
   printf '   implicit none\n'
   printf '   integer, intent(in) :: unit\n'
   printf '   integer, parameter :: flag_width = 56\n'
   printf '   integer :: flag_start, flag_end, flag_len\n'
   printf '\n'
   emit_string FMS_VERSION "$version"
   emit_string GIT_BRANCH "$git_branch"
   emit_string GIT_REVISION "$git_revision"
   emit_string GIT_DIRTY "$git_dirty"
   emit_string BUILD_DATE "$build_date"
   emit_string BUILD_SYSTEM "$build_system"
   emit_string BUILD_TYPE "$build_type"
   emit_string FORTRAN_COMPILER "$fc"
   emit_string FORTRAN_COMPILER_ID "$fc_id"
   emit_string FORTRAN_COMPILER_VERSION "$fc_version"
   emit_string FORTRAN_FLAGS "$fflags"
   emit_string OPENFMS_BACKEND "$backend"
   printf '\n'
   printf "   write (unit, '(1x, a, t25, a)') 'OpenFMS version:', trim(FMS_VERSION)\n"
   printf "   write (unit, '(1x, a, t25, a)') 'git branch:', trim(GIT_BRANCH)\n"
   printf "   write (unit, '(1x, a, t25, a)') 'git revision:', trim(GIT_REVISION)//trim(GIT_DIRTY)\n"
   printf "   write (unit, '(1x, a, t25, a)') 'configuration date:', trim(BUILD_DATE)\n"
   printf "   write (unit, '(1x, a, t25, a)') 'build system:', trim(BUILD_SYSTEM)\n"
   printf "   write (unit, '(1x, a, t25, a)') 'build type:', trim(BUILD_TYPE)\n"
   printf "   write (unit, '(1x, a, t25, a)') 'Fortran compiler:', trim(FORTRAN_COMPILER_ID)//' '//trim(FORTRAN_COMPILER_VERSION)\n"
   printf "   write (unit, '(1x, a, t25, a)') 'Fortran command:', trim(FORTRAN_COMPILER)\n"
   printf "   flag_len = len_trim(FORTRAN_FLAGS)\n"
   printf "   if(flag_len == 0) then\n"
   printf "      write (unit, '(1x, a, t25, a)') 'Fortran flags:', ''\n"
   printf "   else\n"
   printf "      flag_start = 1\n"
   printf "      flag_end = min(flag_len, flag_width)\n"
   printf "      write (unit, '(1x, a, t25, a)') 'Fortran flags:', FORTRAN_FLAGS(flag_start:flag_end)\n"
   printf "      flag_start = flag_end + 1\n"
   printf "      do while(flag_start <= flag_len)\n"
   printf "         flag_end = min(flag_len, flag_start + flag_width - 1)\n"
   printf "         write (unit, '(t25, a)') FORTRAN_FLAGS(flag_start:flag_end)\n"
   printf "         flag_start = flag_end + 1\n"
   printf "      enddo\n"
   printf "   endif\n"
   printf "   write (unit, '(1x, a, t25, a)') 'backend/interface:', trim(OPENFMS_BACKEND)\n"
   printf 'end subroutine print_build_info\n'
   printf '\n'
   printf 'subroutine print_version(unit)\n'
   printf '   implicit none\n'
   printf '   integer, intent(in) :: unit\n'
   printf '\n'
   emit_string FMS_VERSION "$version"
   emit_string GIT_REVISION "$git_revision"
   emit_string GIT_DIRTY "$git_dirty"
   printf '\n'
   printf "   if(len_trim(FMS_VERSION) > 0) then\n"
   printf "      write (unit, '(a)') 'OpenFMS '//trim(FMS_VERSION)//' '//trim(GIT_REVISION)//trim(GIT_DIRTY)\n"
   printf "   else\n"
   printf "      write (unit, '(a)') 'OpenFMS '//trim(GIT_REVISION)//trim(GIT_DIRTY)\n"
   printf "   endif\n"
   printf 'end subroutine print_version\n'
} > "$tmp"

# Avoid changing build_info.F90 when nothing changed, or when the only change
# is BUILD_DATE. Preserving the file timestamp prevents unnecessary recompiles
# and relinks from make with no other changes
if test -f "$output"; then
   if cmp -s "$tmp" "$output"; then
      rm -f "$tmp"
   else
      # Check if only the timestamp changed - if yes, do not regenerate
      old_without_date="${tmp}.old-without-date"
      new_without_date="${tmp}.new-without-date"
      remove_build_date "$output" > "$old_without_date"
      remove_build_date "$tmp" > "$new_without_date"
      if cmp -s "$old_without_date" "$new_without_date"; then
         rm -f "$tmp"
      else
         mv "$tmp" "$output"
      fi
      rm -f "$old_without_date" "$new_without_date"
   fi
else
   mv "$tmp" "$output"
fi
