#!/usr/bin/env python3
"""Discover OpenFMS unit tests and write a small CMake include file."""

import re
from pathlib import Path

SOURCE_DIR = Path(__file__).resolve().parent.parent
OUTPUT = Path.cwd() / "OpenFMSDiscoveredUnitTests.cmake"

TESTSUITE_REGISTRATIONS = re.compile(
    r"new_testsuite\s*\(\s*\"([^\"]+)\"\s*,\s*([A-Za-z_][A-Za-z0-9_]*)",
    re.IGNORECASE | re.MULTILINE,
)
SUITE_COLLECTOR = re.compile(
    r"\bsubroutine\s+(collect_[A-Za-z0-9_]+)\s*\(",
    re.IGNORECASE | re.MULTILINE,
)
UNITTEST_REGISTRATIONS = re.compile(
    r"new_unittest\s*\(\s*\"([^\"]+)\"",
    re.IGNORECASE | re.MULTILINE,
)


def cmake_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def discover_suites(main_source: Path) -> dict[str, str]:
    return {
        suite_collector.lower(): suite_name
        for suite_name, suite_collector in TESTSUITE_REGISTRATIONS.findall(
            read_text(main_source)
        )
    }


def discover_source_tests(test_source: Path) -> tuple[str, list[str]]:
    contents = read_text(test_source)
    suite_collector = SUITE_COLLECTOR.search(contents).group(1)
    test_names = UNITTEST_REGISTRATIONS.findall(contents)
    return suite_collector, test_names


def discover_unit_tests() -> list[tuple[str, str]]:
    unit_test_dir = SOURCE_DIR / "unit_tests"
    suites = discover_suites(unit_test_dir / "main.F90")

    discovered_tests: list[tuple[str, str]] = []
    for test_source in sorted(unit_test_dir.glob("test_*.F90")):
        suite_collector, test_names = discover_source_tests(test_source)
        suite_name = suites[suite_collector.lower()]
        discovered_tests.extend((suite_name, test_name) for test_name in test_names)

    return discovered_tests


def write_cmake_include(output: Path, discovered_tests: list[tuple[str, str]]) -> None:
    lines = [
        "# This file is generated by cmake/discover_openfms_unit_tests.py.",
        "# Do not edit it by hand.",
        "",
    ]
    for suite_name, test_name in discovered_tests:
        lines.append(
            f'openfms_add_discovered_unit_test("{cmake_quote(suite_name)}" "{cmake_quote(test_name)}")'
        )
    lines.append("")

    contents = "\n".join(lines)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(contents, encoding="utf-8")


def main() -> None:
    discovered_tests = discover_unit_tests()
    write_cmake_include(OUTPUT, discovered_tests)


if __name__ == "__main__":
    main()
