include_guard(GLOBAL)

set(OPENFMS_CORE_SOURCES
  src/modules/GlobalModule.f90
  src/modules/EispackModule.f
  src/modules/RandomModule.f90
  src/modules/ParticleModule.f90
  src/modules/ElecStrucModule.f90
  src/modules/QM_MM_Module.f90
  src/modules/TrajectoryModule.f90
  src/modules/ToyModelModule.f90
  src/modules/TemplateModule.f90
  src/modules/TerachemModule.F90
  src/modules/QuanticsModule.F90
  src/modules/SMDModule.f90
  src/modules/RattleModule.f90
  src/modules/TrajectoryCalcsModule.f90
  src/modules/TrajectoryIOModule.f90
  src/modules/OverlapModule.f90
  src/modules/BundleModule.f90
  src/modules/BundleCalcsModule.f90
  src/modules/ThermoModule.f90
  src/modules/RestartModule.f90
  src/modules/VerletModule.f90
  src/modules/SamplingModule.f90
  src/modules/SelectionModule.f90
  src/modules/SpawnModule.f90
  src/modules/BundleIOModule.f90
  src/modules/FMSModule.f90
  src/modules/MinSearchModule.f90
  src/modules/PropagationModule.f90
  src/modules/InitialModule.f90
  src/dynamics.f90
  src/initialcond.f90
  src/minsearch.f90
  src/particle_types.f90
  src/read_geometry.f90
  src/read_namelist.f90
  src/remove_dead.f90
  src/shutdown.f90
)
