name: Lint & Format

# Run various static checks and autoformatter, using prek

on:
  push:
    branches: [ main ]
  pull_request:

env:
  FORCE_COLOR: 1

jobs:

  prek:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      SKIP: 'no-commit-to-branch'

    steps:
    - uses: actions/checkout@v6

    - name: Install prek
      # Configargparse is needed for the fprettify autoformatter
      run: pip install prek configargparse

    - name: Run prek hooks
      run: prek run --all-files --show-diff-on-failure --color always
